controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reservation_agenda:
    path: /reservation/agenda
    controller: App\Controller\ReservationController::agenda
    methods: [GET, POST]
    requirements:
        year: '\d+'
        month: '\d+'
