controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reservation_index:
    path: /reservation
    controller: App\Controller\ReservationController::index

reservation_new:
    path: /reservation/new
    controller: App\Controller\ReservationController::new

reservation_calendar:
    path: /reservation/calendar
    controller: App\Controller\ReservationController::calendar
